### ISSUE TITLE
Error: [rebrowser-patches] acquireContextId failed 

### ISSUE THREAD

**Issue by Sh1d0w** [rebrowser/rebrowser-patches#70]
I am getting this error when I try to open this website https://lorcoffee.com

Other websites work normally, not sure what is the root cause.

For context I am using https://www.npmjs.com/package/@axe-core/puppeteer to scan the page and I have setLegacyMode(true) that's when it breaks

**Comment by nwebson** [comment]
Just released a new version, this issue should be fixed there.
https://github.com/rebrowser/rebrowser-patches/releases/tag/1.0.16

**Comment by Sh1d0w** [comment]
Thanks for the quick fix @nwebson !

However I am not sure it works, I've installed version 23.10.1 of rebrowser/puppeteer and still getting the error:

```
[rebrowser-patches] acquireContextId failed (tryAgain = true, tryCount = 3), errorMessage: N/A","stack":"Error: [rebrowser-patches] acquireContextId failed (tryAgain = true, tryCount = 3), errorMessage: N/A\n at ExecutionContext.acquireContextId
```

**Comment by nwebson** [comment]
Could you provide full code, so I can try to reproduce it locally?

**Comment by nwebson** [comment]
Also, you could try to run it with `DEBUG="puppeteer:*" node app.js`, and copy some lines of logs before this error, that would give me more context on this issue.

**Comment by Sh1d0w** [comment]
@nwebson Actually it is working just fine, it was my mistake, seems like some node_modules cache, but once I removed and did clean install it works perfectly. Thanks!

**Comment by nwebson** [comment]
Based on your latest error message it was from the latest version 🤔  so, you might see this error again

**Comment by Sh1d0w** [comment]
Yeah, it is weird indeed, I am sure I've installed the latest version properly, then it failed. I've removed node modules and package-lock.json and re-installed and it does not occur anymore. Here is example code I've used to test:

```
const { AxePuppeteer } = require("@axe-core/puppeteer");
const puppeteer = require("rebrowser-puppeteer");

const run = async () => {
  const browser = await puppeteer.launch({ headless: true });
  const pages = await browser.pages();
  const page = pages[0];
  await page.goto("https://lorcoffee.com", { waitUntil: "networkidle2" });

  const axeResults = await new AxePuppeteer(page)
    .options({
      resultTypes: ["violations"],
      rules: {
        "frame-tested": { enabled: false },
        "target-size": { enabled: true },
        "color-contrast-enhanced": { enabled: false },
        "identical-links-same-purpose": { enabled: false },
        "meta-refresh-no-exceptions": { enabled: false },
      },
    })
    .setLegacyMode(true)
    .analyze();

  console.log(axeResults);
  await browser.close();
};

run();
```

I don't want to take anymore of your time for now, but if it happens again I will provide more info with debug logs, for now it seems your fix worked as it does not happen anymore.
